mqtt:
  brokers:
    - "mqtt://127.0.0.1:1883"
  client_id: "atm-backend"

  topics: # ATM devices' topics
    - "pulseacceptord"
    - "codescannerd"

log_format: "pretty"
log_file: "log.txt"
mode: "mainnet"
fee: 1
moneropay: "192.168.1.129:5000"
price_poll_frequency: "5m"
currency_short: "EUR"
motd: "Welcome to MoneroKon 2023!"
